name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install dependencies
        run: mvn package -DskipTests
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v2
        with: # running setup-java again overwrites the settings.xml
         server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
         server-username: ${{ secrets.OSSRH_USERNAME }} # env variable for username in deploy
         server-password: ${{ secrets.OSSRH_PASSWORD }}
         gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
         gpg-passphrase: ${{ MAVEN_GPG_PASSPHRASE }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify -Dpgp.skip-true
      - name: Run Formatter
        run: mvn com.coveo:fmt-maven-plugin:format
      - name: Test
        run: mvn test

